name: jg-go-snaps-helloworld
version: git
summary:  A starter example of how to package a go app into a snap
description: |
  A starter example of how to package a go app into a snap

grade: devel
confinement: devmode

parts:
  go-snaps-helloworld:
    source: .
    source-branch: gphotos-uploader-cli
    plugin: go
    go-importpath: github.com/promofu/hello-snapcraft-go
apps:
  go-snaps-helloworld:
    command: snapcraft-go-helloworld
